languages = {
    "English": {
        "update_text": "Update Text",
        "change_text_color": "Change Text Color",
        "change_bg_color": "Change Background Color",
        "adjust_font_size": "Adjust Font Size",
        "toggle_text": "Toggle Text",
        "guide_text": "Guide:\n\n- Enter your text in the text area.\n- Use the buttons to change text and background colors.\n- Adjust font size with the 'Adjust Font Size' button.\n- Drag the text by clicking and dragging.\n- Toggle the text window visibility using 'Toggle Text'.",
        "language": "Language",
        "font_size_title": "Font Size",
        "font_size_prompt": "Enter font size:",
        "save_confirmation": "Do you want to save this text?",
        "save_yes": "Yes",
        "save_no": "No",
        "save_cancel": "Cancel",
        "options": "Options",
        "help": "Help",
        "guide": "Guide"
    },
    "Vietnamese": {
        "update_text": "Cập nhật văn bản",
        "change_text_color": "Đổi màu văn bản",
        "change_bg_color": "Đổi màu nền",
        "adjust_font_size": "Điều chỉnh cỡ chữ",
        "toggle_text": "Bật/Tắt văn bản",
        "guide_text": "Hướng dẫn:\n\n- Nhập văn bản vào ô.\n- Sử dụng các nút để thay đổi màu văn bản và nền.\n- Điều chỉnh cỡ chữ bằng nút 'Điều chỉnh cỡ chữ'.\n- Kéo văn bản bằng cách bấm và kéo.\n- Bật/Tắt cửa sổ văn bản.",
        "language": "Ngôn ngữ",
        "font_size_title": "Cỡ chữ",
        "font_size_prompt": "Nhập cỡ chữ:",
        "save_confirmation": "Bạn có muốn lưu văn bản này không?",
        "save_yes": "Có",
        "save_no": "Không",
        "save_cancel": "Hủy",
        "options": "Tùy chọn",
        "help": "Trợ giúp",
        "guide": "Hướng dẫn"
    },
    "Japanese": {
        "update_text": "テキストを更新",
        "change_text_color": "テキストの色を変更",
        "change_bg_color": "背景色を変更",
        "adjust_font_size": "フォントサイズを調整",
        "toggle_text": "テキストを切り替え",
        "guide_text": "ガイド:\n\n- テキストエリアに入力します。\n- ボタンを使ってテキストや背景色を変更します。\n- 'フォントサイズを調整' ボタンでサイズを調整します。\n- テキストをクリックしてドラッグします。\n- 「テキストを切り替え」を使用してウィンドウの表示/非表示を切り替えます。",
        "language": "言語",
        "font_size_title": "フォントサイズ",
        "font_size_prompt": "フォントサイズを入力してください:",
        "save_confirmation": "このテキストを保存しますか？",
        "save_yes": "はい",
        "save_no": "いいえ",
        "save_cancel": "キャンセル",
        "options": "オプション",
        "help": "ヘルプ",
        "guide": "ガイド"
    },
    "Chinese": {
        "update_text": "更新文字",
        "change_text_color": "更改文字颜色",
        "change_bg_color": "更改背景颜色",
        "adjust_font_size": "调整字体大小",
        "toggle_text": "切换文本",
        "guide_text": "指南:\n\n- 在文本区域输入文字。\n- 使用按钮更改文本和背景颜色。\n- 使用“调整字体大小”按钮调整字体大小。\n- 点击并拖动文本。\n- 使用“切换文本”按钮切换文本窗口的显示。",
        "language": "语言",
        "font_size_title": "字体大小",
        "font_size_prompt": "输入字体大小：",
        "save_confirmation": "您要保存此文本吗？",
        "save_yes": "是",
        "save_no": "否",
        "save_cancel": "取消",
        "options": "选项",
        "help": "帮助",
        "guide": "指南"
    }
}
